[tool.poetry]
name = "PINNintro"
version = "0.1.0"
description = ""
authors = ["Sima"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
